import { useQuery, useMutation, useQueryClient } from "@tanstack/react-query";
import { supabase } from "@/integrations/supabase/client";
import { useToast } from "@/hooks/use-toast";

export interface FormulaMagistral {
  id: string;
  codigo: string;
  nuevo_codigo?: string | null;
  descripcion: string;
  presentation: string;
  stock_actual: number;
  precio_venta?: number;
  formula_magistral: boolean;
}

export interface PedidoFormulaMagistral {
  id: string;
  nro_formula: string;
  formula: string;
  codigo_producto?: string;
  id_paciente?: string;
  numero_contacto?: string;
  cantidad: number;
  monto_pedido?: number;
  observaciones?: string;
  created_at: string;
  patient?: {
    first_name: string;
    last_name: string;
    dni: string;
  };
}

export const useFormulasMagistrales = () => {
  return useQuery({
    queryKey: ["formulas-magistrales"],
    queryFn: async () => {
      const { data, error } = await supabase
        .from("pharmacy_medications")
        .select("*")
        .eq("formula_magistral", true)
        .eq("status", "Activo")
        .order("descripcion");
      
      if (error) throw error;
      return data as FormulaMagistral[];
    },
  });
};

export const usePedidosFormulasMagistrales = () => {
  return useQuery({
    queryKey: ["pedidos-formulas-magistrales"],
    queryFn: async () => {
      const { data, error } = await supabase
        .from("pedido_formula_magistral")
        .select(`
          *,
          patient:patients(first_name, last_name, dni)
        `)
        .order("created_at", { ascending: false });
      
      if (error) throw error;
      return data as PedidoFormulaMagistral[];
    },
  });
};

export const useCreatePedidoFormulaMagistral = () => {
  const queryClient = useQueryClient();
  const { toast } = useToast();

  return useMutation({
    mutationFn: async (pedido: {
      formula: string;
      id_paciente?: string;
      numero_contacto?: string;
      cantidad: number;
      monto_pedido?: number;
      observaciones?: string;
    }) => {
      const { data, error } = await supabase
        .from("pedido_formula_magistral")
        .insert([{ ...pedido, nro_formula: '' }]) // Will be auto-generated by trigger
        .select()
        .single();

      if (error) throw error;
      return data;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["pedidos-formulas-magistrales"] });
      toast({
        title: "Pedido registrado",
        description: "El pedido de fórmula magistral se ha registrado correctamente.",
      });
    },
    onError: (error) => {
      toast({
        title: "Error",
        description: "No se pudo registrar el pedido.",
        variant: "destructive",
      });
    },
  });
};
