TRUNCATE TABLE public.enfermedades;

INSERT INTO public.enfermedades (cie10_clase, clase, cie10_enfermedad, nombre_enfermedad, vista_cie10) VALUES
('A00 - A09', 'ENFERMEDADES INFECCIOSAS INTESTINALES', 'A000', 'COLERA DEBIDO A VIBRIO CHOLERAE 01, BIOTIPO CHOLERAE', 'A00 - A09 - ENFERMEDADES INFECCIOSAS INTESTINALES'),
('A00 - A09', 'ENFERMEDADES INFECCIOSAS INTESTINALES', 'A001', 'COLERA DEBIDO A VIBRIO CHOLERAE 01, BIOTIPO EL TOR', 'A00 - A09 - ENFERMEDADES INFECCIOSAS INTESTINALES'),
('A00 - A09', 'ENFERMEDADES INFECCIOSAS INTESTINALES', 'A009', 'COLERA, NO ESPECIFICADO', 'A00 - A09 - ENFERMEDADES INFECCIOSAS INTESTINALES'),
('A00 - A09', 'ENFERMEDADES INFECCIOSAS INTESTINALES', 'A0090', 'SOSPECHOSO DE COLERA', 'A00 - A09 - ENFERMEDADES INFECCIOSAS INTESTINALES'),
('A00 - A09', 'ENFERMEDADES INFECCIOSAS INTESTINALES', 'A0091', 'SOSPECHOSO DE COLERA NO ESPECIFICADO SIN DESHIDRATACION', 'A00 - A09 - ENFERMEDADES INFECCIOSAS INTESTINALES');