-- Insertar conceptos de dermatología desde PDF
-- Página 1: Procedimientos principales
INSERT INTO concepto (nombre, descripcion, tipo, monto, activo) VALUES
('ACIDO HIALURONICO', NULL, 'dermatologia', 750, true),
('PROFHILO', NULL, 'dermatologia', 1450, true),
('SAYPHA RICH', NULL, 'dermatologia', 950, true),
('LIPASA LIQUIDA', NULL, 'dermatologia', 300, true),
('LIPASA POLVO', NULL, 'dermatologia', 350, true),
('PEELING BIOREPEEL CARA O CUERPO', NULL, 'dermatologia', 200, true),
('LENISNA', NULL, 'dermatologia', 1800, true),
('GOURI', NULL, 'dermatologia', 1200, true),
('JUVE LOOK', NULL, 'dermatologia', 2500, true),
('RADIESSE', NULL, 'dermatologia', 2000, true),
('TKN HA', NULL, 'dermatologia', 930, true),
('TKN HA+ANTI AGING', NULL, 'dermatologia', 1250, true),
('ANTI-HAIR LOSS', NULL, 'dermatologia', 210, true),
('ANTI-AGING', NULL, 'dermatologia', 300, true),
('ECPR (PERIOCULAR) QUINCENAL O MENSUAL', 'Sesión', 'dermatologia', 150, true),
('HCPR (FORTIFICADOR DEL CABELLO) QUINCENAL O MENSUAL', 'Sesión', 'dermatologia', 150, true),
('INFILTRACION DE BLEOMICINA 0.5ML', NULL, 'dermatologia', 100, true),
('INFILTRACION DE BLEOMICINA 0.1ML', NULL, 'dermatologia', 50, true),
('INFILTRACION DE BLEOMICINA 1ML', NULL, 'dermatologia', 200, true),
('INFILTRACION DE TRIAMCINOLONA 0.1ML', NULL, 'dermatologia', 80, true),
('INFILTRACION DE TRIAMCINOLONA 1ML', NULL, 'dermatologia', 160, true),
('APLICACION DE ACIDO TRANEXAMICO 1ML', NULL, 'dermatologia', 100, true),

-- Página 2: Exosomas, IPL, Láser y otros procedimientos
('EXOSOMAS CAPILAR 5 VIALES (MENSUAL)', 'USD $1560', 'dermatologia', 5757, true),
('IPL MAS ACIDO TRANEXAMICO', NULL, 'dermatologia', 250, true),
('IPL MAS MASCARA DE ACIDO HIALURONICO', NULL, 'dermatologia', 250, true),
('IPL', NULL, 'dermatologia', 200, true),
('LASER QS LENTIGOS SOLARES', NULL, 'dermatologia', 300, true),
('LASER QS TATUAJES', NULL, 'dermatologia', 150, true),
('LASER QS ONICOMICOSIS LOS DOS PIES', NULL, 'dermatologia', 200, true),
('LASER QS ONICOMICOSIS LOS DOS PIES UÑAS', NULL, 'dermatologia', 100, true),
('LASER CO2 LESIONES', NULL, 'dermatologia', 100, true),
('LASER CO2 FULL FACE', NULL, 'dermatologia', 1300, true),
('CRIOTERAPIA 1-4 LESIONES', NULL, 'dermatologia', 50, true),
('CRIOTERAPIA DE 5-10 LESIONES', NULL, 'dermatologia', 250, true),
('CRIOTERAPIA MAS DE 10 LESIONES', NULL, 'dermatologia', 350, true),
('ELECTROCAUTERIZACION CUELLO ANTERIOR', NULL, 'dermatologia', 150, true),
('ELECTROCAUTERIZACION CUELLO POSTERIOR', NULL, 'dermatologia', 150, true),
('ELECTROCAUTERIZACION PARPADOS SUPERIORES', NULL, 'dermatologia', 100, true),
('ELECTROCAUTERIZACION PARPADOS INFERIORES', NULL, 'dermatologia', 100, true),
('ELECTROCAUTERIZACION HEMICARA', NULL, 'dermatologia', 100, true),
('ELECTROCAUTERIZACION TODO LA CARA', NULL, 'dermatologia', 350, true),
('MICRODERMOABRASION', NULL, 'dermatologia', 150, true),
('LIMPIEZA FACIAL', NULL, 'dermatologia', 150, true),
('VITAMINA C ENDOVENOSA', NULL, 'dermatologia', 150, true),
('BIOPSIA DE PIEL', NULL, 'dermatologia', 150, true),
('EXCERECIS DE LESION O LUNAR', NULL, 'dermatologia', 100, true),

-- Página 3: Nanopore, Plaquetas, Ultracavitador y depilación láser
('NANOPORE', NULL, 'dermatologia', 320, true),
('PLAQUETAS', NULL, 'dermatologia', 200, true),
('ULTRACAVITADOR 6 SESIONES', 'Remover células adiposas, combatir la flacidez, reducción de medidas, drenar tejido adiposo, activación de la circulación', 'dermatologia', 1200, true),
('DEPILACION LASER DIODO AXILAS', NULL, 'dermatologia', 60, true),
('DEPILACION LASER DIODO ROSTRO', NULL, 'dermatologia', 90, true),
('DEPILACION LASER DIODO BOZO', NULL, 'dermatologia', 40, true),
('DEPILACION LASER DIODO PIERNA', NULL, 'dermatologia', 190, true),
('DEPILACION LASER DIODO BRAZO', NULL, 'dermatologia', 120, true),
('DEPILACION LASER DIODO PECHO', NULL, 'dermatologia', 100, true),
('DEPILACION LASER DIODO ABDOMEN', NULL, 'dermatologia', 100, true),
('DEPILACION LASER DIODO BIKINI', NULL, 'dermatologia', 130, true),
('DEPILACION LASER DIODO ESPALDA', NULL, 'dermatologia', 140, true)
ON CONFLICT DO NOTHING;