
-- Crear tabla de enfermedades con clasificación CIE10
CREATE TABLE public.enfermedades (
  id UUID NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  cie10_clase TEXT NOT NULL,
  clase TEXT NOT NULL,
  cie10_enfermedad TEXT NOT NULL,
  nombre_enfermedad TEXT NOT NULL,
  vista_cie10 TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);

-- Crear índice para búsquedas rápidas
CREATE INDEX idx_enfermedades_vista_cie10 ON public.enfermedades USING gin(to_tsvector('spanish', vista_cie10));
CREATE INDEX idx_enfermedades_cie10 ON public.enfermedades (cie10_enfermedad);

-- Insertar datos de ejemplo basados en la imagen
INSERT INTO public.enfermedades (cie10_clase, clase, cie10_enfermedad, nombre_enfermedad, vista_cie10) VALUES
('C00-C97', 'TUMORES MALIGNOS', 'C09', 'TUMOR MALIGNO DE LA AMIGDALA', 'C09 - TUMOR MALIGNO DE LA AMIGDALA'),
('C00-C97', 'TUMORES MALIGNOS', 'C090', 'TUMOR MALIGNO DE LA FOSA AMIGDALINA', 'C090 - TUMOR MALIGNO DE LA FOSA AMIGDALINA'),
('C00-C97', 'TUMORES MALIGNOS', 'C091', 'TUMOR MALIGNO DEL PILAR AMIGDALINO (ANTERIOR) (POSTERIOR)', 'C091 - TUMOR MALIGNO DEL PILAR AMIGDALINO (ANTERIOR) (POSTERIOR)'),
('C00-C97', 'TUMORES MALIGNOS', 'C098', 'LESION DE SITIOS CONTIGUOS DE LA AMIGDALA', 'C098 - LESION DE SITIOS CONTIGUOS DE LA AMIGDALA'),
('C00-C97', 'TUMORES MALIGNOS', 'C099', 'TUMOR MALIGNO DE LA AMIGDALA, PARTE NO ESPECIFICADA', 'C099 - TUMOR MALIGNO DE LA AMIGDALA, PARTE NO ESPECIFICADA'),
('C00-C97', 'TUMORES MALIGNOS', 'C10', 'TUMOR MALIGNO DE LA OROFARINGE', 'C10 - TUMOR MALIGNO DE LA OROFARINGE'),
('C00-C97', 'TUMORES MALIGNOS', 'C100', 'TUMOR MALIGNO DE LA VALECULA', 'C100 - TUMOR MALIGNO DE LA VALECULA'),
('C00-C97', 'TUMORES MALIGNOS', 'C101', 'TUMOR MALIGNO DE LA CARA ANTERIOR DE LA EPIGLOTIS', 'C101 - TUMOR MALIGNO DE LA CARA ANTERIOR DE LA EPIGLOTIS'),
('C00-C97', 'TUMORES MALIGNOS', 'C102', 'TUMOR MALIGNO DE LA PARED LATERAL DE LA OROFARINGE', 'C102 - TUMOR MALIGNO DE LA PARED LATERAL DE LA OROFARINGE'),
('C00-C97', 'TUMORES MALIGNOS', 'C103', 'TUMOR MALIGNO DE LA PARED POSTERIOR DE LA OROFARINGE', 'C103 - TUMOR MALIGNO DE LA PARED POSTERIOR DE LA OROFARINGE'),
('C00-C97', 'TUMORES MALIGNOS', 'C104', 'TUMOR MALIGNO DE LA HENDIDURA BRANQUIAL', 'C104 - TUMOR MALIGNO DE LA HENDIDURA BRANQUIAL'),
('C00-C97', 'TUMORES MALIGNOS', 'C108', 'LESION DE SITIOS CONTIGUOS DE LA OROFARINGE', 'C108 - LESION DE SITIOS CONTIGUOS DE LA OROFARINGE'),
('C00-C97', 'TUMORES MALIGNOS', 'C109', 'TUMOR MALIGNO DE LA OROFARINGE, PARTE NO ESPECIFICADA', 'C109 - TUMOR MALIGNO DE LA OROFARINGE, PARTE NO ESPECIFICADA'),
('C00-C97', 'TUMORES MALIGNOS', 'C11', 'TUMOR MALIGNO DE LA NASOFARINGE', 'C11 - TUMOR MALIGNO DE LA NASOFARINGE'),
('C00-C97', 'TUMORES MALIGNOS', 'C110', 'TUMOR MALIGNO DE LA PARED SUPERIOR DE LA NASOFARINGE', 'C110 - TUMOR MALIGNO DE LA PARED SUPERIOR DE LA NASOFARINGE'),
('C00-C97', 'TUMORES MALIGNOS', 'C111', 'TUMOR MALIGNO DE LA PARED POSTERIOR DE LA NASOFARINGE', 'C111 - TUMOR MALIGNO DE LA PARED POSTERIOR DE LA NASOFARINGE'),
('C00-C97', 'TUMORES MALIGNOS', 'C112', 'TUMOR MALIGNO DE LA PARED LATERAL DE LA NASOFARINGE', 'C112 - TUMOR MALIGNO DE LA PARED LATERAL DE LA NASOFARINGE'),
('C00-C97', 'TUMORES MALIGNOS', 'C113', 'TUMOR MALIGNO DE LA PARED ANTERIOR DE LA NASOFARINGE', 'C113 - TUMOR MALIGNO DE LA PARED ANTERIOR DE LA NASOFARINGE'),
('C00-C97', 'TUMORES MALIGNOS', 'C118', 'LESION DE SITIOS CONTIGUOS DE LA NASOFARINGE', 'C118 - LESION DE SITIOS CONTIGUOS DE LA NASOFARINGE'),
('C00-C97', 'TUMORES MALIGNOS', 'C119', 'TUMOR MALIGNO DE LA NASOFARINGE, PARTE NO ESPECIFICADA', 'C119 - TUMOR MALIGNO DE LA NASOFARINGE, PARTE NO ESPECIFICADA'),
('C00-C97', 'TUMORES MALIGNOS', 'C12', 'TUMOR MALIGNO DEL SENO PIRIFORME', 'C12 - TUMOR MALIGNO DEL SENO PIRIFORME'),
('C00-C97', 'TUMORES MALIGNOS', 'C12X', 'TUMOR MALIGNO DEL SENO PIRIFORME', 'C12X - TUMOR MALIGNO DEL SENO PIRIFORME'),
('C00-C97', 'TUMORES MALIGNOS', 'C13', 'TUMOR MALIGNO DE LA HIPOFARINGE', 'C13 - TUMOR MALIGNO DE LA HIPOFARINGE'),
('C00-C97', 'TUMORES MALIGNOS', 'C130', 'TUMOR MALIGNO DE LA REGION POSTCRICOIDEA', 'C130 - TUMOR MALIGNO DE LA REGION POSTCRICOIDEA'),
('C00-C97', 'TUMORES MALIGNOS', 'C131', 'TUMOR MALIGNO DEL PLIEGUE ARITENOEPIGLOTICO, CARA HIPOFARINGEA', 'C131 - TUMOR MALIGNO DEL PLIEGUE ARITENOEPIGLOTICO, CARA HIPOFARINGEA'),
('C00-C97', 'TUMORES MALIGNOS', 'C132', 'TUMOR MALIGNO DE LA PARED POSTERIOR DE LA HIPOFARINGE', 'C132 - TUMOR MALIGNO DE LA PARED POSTERIOR DE LA HIPOFARINGE'),
('C00-C97', 'TUMORES MALIGNOS', 'C138', 'LESION DE SITIOS CONTIGUOS DE LA HIPOFARINGE', 'C138 - LESION DE SITIOS CONTIGUOS DE LA HIPOFARINGE'),
('C00-C97', 'TUMORES MALIGNOS', 'C139', 'TUMOR MALIGNO DE LA HIPOFARINGE, PARTE NO ESPECIFICADA', 'C139 - TUMOR MALIGNO DE LA HIPOFARINGE, PARTE NO ESPECIFICADA');

-- Habilitar RLS para la tabla de enfermedades
ALTER TABLE public.enfermedades ENABLE ROW LEVEL SECURITY;

-- Política para permitir lectura a todos los usuarios autenticados
CREATE POLICY "Todos pueden ver enfermedades" 
  ON public.enfermedades 
  FOR SELECT 
  USING (true);

-- Política para permitir inserción solo a administradores
CREATE POLICY "Solo administradores pueden agregar enfermedades" 
  ON public.enfermedades 
  FOR INSERT 
  WITH CHECK (public.is_admin());

-- Política para permitir actualización solo a administradores  
CREATE POLICY "Solo administradores pueden actualizar enfermedades" 
  ON public.enfermedades 
  FOR UPDATE 
  USING (public.is_admin());

-- Política para permitir eliminación solo a administradores
CREATE POLICY "Solo administradores pueden eliminar enfermedades" 
  ON public.enfermedades 
  FOR DELETE 
  USING (public.is_admin());
