-- Limpiar tabla enfermedades y cargar datos actualizados del CIE10
TRUNCATE TABLE public.enfermedades;

-- Insertar datos actualizados del CIE10
INSERT INTO public.enfermedades (cie10_clase, clase, cie10_enfermedad, nombre_enfermedad, vista_cie10) VALUES
-- ENFERMEDADES INFECCIOSAS INTESTINALES (A00-A09)
('A00 - A09', 'ENFERMEDADES INFECCIOSAS INTESTINALES', 'A000', 'COLERA DEBIDO A VIBRIO CHOLERAE 01, BIOTIPO CHOLERAE', 'A000 - COLERA DEBIDO A VIBRIO CHOLERAE 01, BIOTIPO CHOLERAE'),
('A00 - A09', 'ENFERMEDADES INFECCIOSAS INTESTINALES', 'A001', 'COLERA DEBIDO A VIBRIO CHOLERAE 01, BIOTIPO EL TOR', 'A001 - COLERA DEBIDO A VIBRIO CHOLERAE 01, BIOTIPO EL TOR'),
('A00 - A09', 'ENFERMEDADES INFECCIOSAS INTESTINALES', 'A009', 'COLERA, NO ESPECIFICADO', 'A009 - COLERA, NO ESPECIFICADO'),
('A00 - A09', 'ENFERMEDADES INFECCIOSAS INTESTINALES', 'A0090', 'SOSPECHOSO DE COLERA', 'A0090 - SOSPECHOSO DE COLERA'),
('A00 - A09', 'ENFERMEDADES INFECCIOSAS INTESTINALES', 'A0091', 'SOSPECHOSO DE COLERA NO ESPECIFICADO SIN DESHIDRATACION', 'A0091 - SOSPECHOSO DE COLERA NO ESPECIFICADO SIN DESHIDRATACION'),
('A00 - A09', 'ENFERMEDADES INFECCIOSAS INTESTINALES', 'A0092', 'SOSPECHOSOS DE COLERA NO ESPECIFICADO CON DESHIDRATACION', 'A0092 - SOSPECHOSOS DE COLERA NO ESPECIFICADO CON DESHIDRATACION'),
('A00 - A09', 'ENFERMEDADES INFECCIOSAS INTESTINALES', 'A0093', 'SOSPECHOSOS DE COLERA NO ESPECIFICADO CON DESHIDRATACION CON SHOCK', 'A0093 - SOSPECHOSOS DE COLERA NO ESPECIFICADO CON DESHIDRATACION CON SHOCK'),
('A00 - A09', 'ENFERMEDADES INFECCIOSAS INTESTINALES', 'A010', 'FIEBRE TIFOIDEA', 'A010 - FIEBRE TIFOIDEA'),
('A00 - A09', 'ENFERMEDADES INFECCIOSAS INTESTINALES', 'A0109', 'FIEBRE TIFOIDEA CON DIARREA', 'A0109 - FIEBRE TIFOIDEA CON DIARREA'),
('A00 - A09', 'ENFERMEDADES INFECCIOSAS INTESTINALES', 'A011', 'FIEBRE PARATIFOIDEA A', 'A011 - FIEBRE PARATIFOIDEA A'),
('A00 - A09', 'ENFERMEDADES INFECCIOSAS INTESTINALES', 'A012', 'FIEBRE PARATIFOIDEA B', 'A012 - FIEBRE PARATIFOIDEA B'),
('A00 - A09', 'ENFERMEDADES INFECCIOSAS INTESTINALES', 'A013', 'FIEBRE PARATIFOIDEA C', 'A013 - FIEBRE PARATIFOIDEA C'),
('A00 - A09', 'ENFERMEDADES INFECCIOSAS INTESTINALES', 'A014', 'FIEBRE PARATIFOIDEA, NO ESPECIFICADA', 'A014 - FIEBRE PARATIFOIDEA, NO ESPECIFICADA'),
('A00 - A09', 'ENFERMEDADES INFECCIOSAS INTESTINALES', 'A0141', 'FIEBRE PARATIFOIDEA NO ESPECIFICADA CON DIARREA', 'A0141 - FIEBRE PARATIFOIDEA NO ESPECIFICADA CON DIARREA'),
('A00 - A09', 'ENFERMEDADES INFECCIOSAS INTESTINALES', 'A020', 'ENTERITIS DEBIDA A SALMONELLA', 'A020 - ENTERITIS DEBIDA A SALMONELLA'),
('A00 - A09', 'ENFERMEDADES INFECCIOSAS INTESTINALES', 'A021', 'SEPSIS DEBIDA A SALMONELLA', 'A021 - SEPSIS DEBIDA A SALMONELLA'),
('A00 - A09', 'ENFERMEDADES INFECCIOSAS INTESTINALES', 'A022', 'INFECCIONES LOCALIZADAS DEBIDAS A SALMONELLA', 'A022 - INFECCIONES LOCALIZADAS DEBIDAS A SALMONELLA'),
('A00 - A09', 'ENFERMEDADES INFECCIOSAS INTESTINALES', 'A028', 'OTRAS INFECCIONES ESPECIFICADAS COMO DEBIDAS A SALMONELLA', 'A028 - OTRAS INFECCIONES ESPECIFICADAS COMO DEBIDAS A SALMONELLA'),
('A00 - A09', 'ENFERMEDADES INFECCIOSAS INTESTINALES', 'A029', 'INFECCION DEBIDA A SALMONELLA, NO ESPECIFICADA', 'A029 - INFECCION DEBIDA A SALMONELLA, NO ESPECIFICADA'),
('A00 - A09', 'ENFERMEDADES INFECCIOSAS INTESTINALES', 'A030', 'SHIGELOSIS DEBIDA A SHIGELLA DYSENTERIAE', 'A030 - SHIGELOSIS DEBIDA A SHIGELLA DYSENTERIAE'),
('A00 - A09', 'ENFERMEDADES INFECCIOSAS INTESTINALES', 'A031', 'SHIGELOSIS DEBIDA A SHIGELLA FLEXNERI', 'A031 - SHIGELOSIS DEBIDA A SHIGELLA FLEXNERI'),
('A00 - A09', 'ENFERMEDADES INFECCIOSAS INTESTINALES', 'A032', 'SHIGELOSIS DEBIDA A SHIGELLA BOYDII', 'A032 - SHIGELOSIS DEBIDA A SHIGELLA BOYDII'),
('A00 - A09', 'ENFERMEDADES INFECCIOSAS INTESTINALES', 'A033', 'SHIGELOSIS DEBIDA A SHIGELLA SONNEI', 'A033 - SHIGELOSIS DEBIDA A SHIGELLA SONNEI'),
('A00 - A09', 'ENFERMEDADES INFECCIOSAS INTESTINALES', 'A038', 'OTRAS SHIGELOSIS', 'A038 - OTRAS SHIGELOSIS'),
('A00 - A09', 'ENFERMEDADES INFECCIOSAS INTESTINALES', 'A039', 'SHIGELOSIS DE TIPO NO ESPECIFICADO', 'A039 - SHIGELOSIS DE TIPO NO ESPECIFICADO'),
('A00 - A09', 'ENFERMEDADES INFECCIOSAS INTESTINALES', 'A040', 'INFECCION DEBIDA A ESCHERICHIA COLI ENTEROPATOGENA', 'A040 - INFECCION DEBIDA A ESCHERICHIA COLI ENTEROPATOGENA'),
('A00 - A09', 'ENFERMEDADES INFECCIOSAS INTESTINALES', 'A041', 'INFECCION DEBIDA A ESCHERICHIA COLI ENTEROTOXIGENA', 'A041 - INFECCION DEBIDA A ESCHERICHIA COLI ENTEROTOXIGENA'),
('A00 - A09', 'ENFERMEDADES INFECCIOSAS INTESTINALES', 'A042', 'INFECCION DEBIDA A ESCHERICHIA COLI ENTEROINVASIVA', 'A042 - INFECCION DEBIDA A ESCHERICHIA COLI ENTEROINVASIVA'),
('A00 - A09', 'ENFERMEDADES INFECCIOSAS INTESTINALES', 'A043', 'INFECCION DEBIDA A ESCHERICHIA COLI ENTEROHEMORRAGICA', 'A043 - INFECCION DEBIDA A ESCHERICHIA COLI ENTEROHEMORRAGICA'),
('A00 - A09', 'ENFERMEDADES INFECCIOSAS INTESTINALES', 'A044', 'OTRAS INFECCIONES INTESTINALES DEBIDAS A ESCHERICHIA COLI', 'A044 - OTRAS INFECCIONES INTESTINALES DEBIDAS A ESCHERICHIA COLI'),
('A00 - A09', 'ENFERMEDADES INFECCIOSAS INTESTINALES', 'A045', 'ENTERITIS DEBIDA A CAMPYLOBACTER', 'A045 - ENTERITIS DEBIDA A CAMPYLOBACTER'),
('A00 - A09', 'ENFERMEDADES INFECCIOSAS INTESTINALES', 'A046', 'ENTERITIS DEBIDA A YERSINIA ENTEROCOLITICA', 'A046 - ENTERITIS DEBIDA A YERSINIA ENTEROCOLITICA'),
('A00 - A09', 'ENFERMEDADES INFECCIOSAS INTESTINALES', 'A047', 'ENTEROCOLITIS DEBIDA A CLOSTRIDIUM DIFFICILE', 'A047 - ENTEROCOLITIS DEBIDA A CLOSTRIDIUM DIFFICILE'),
('A00 - A09', 'ENFERMEDADES INFECCIOSAS INTESTINALES', 'A048', 'OTRAS INFECCIONES INTESTINALES BACTERIANAS ESPECIFICADAS', 'A048 - OTRAS INFECCIONES INTESTINALES BACTERIANAS ESPECIFICADAS'),
('A00 - A09', 'ENFERMEDADES INFECCIOSAS INTESTINALES', 'A049', 'INFECCION INTESTINAL BACTERIANA, NO ESPECIFICADA', 'A049 - INFECCION INTESTINAL BACTERIANA, NO ESPECIFICADA');

-- Nota: Este es un archivo muy extenso con miles de enfermedades del CIE10.
-- Por razones prácticas, esta migración incluye una muestra inicial.
-- Se recomienda usar un script de carga masiva para importar el archivo completo.
