// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yxjjodjpumynmklmhuox.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl4ampvZGpwdW15bm1rbG1odW94Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkyMTM3NTQsImV4cCI6MjA2NDc4OTc1NH0.6HTU_KPHI095UqGSDofxF-zGa7ukOJbk-BSmvJIElu4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);